apiVersion: v1
kind: Service
metadata:
  name: kaurgak-mu-aks-react
  namespace: kaurgak
  
spec:
  type: LoadBalancer
  selector:
    app: kaurgak-mu-aks-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80